#!/bin/bash
##WRITTEN BY: KOEN VAN DER KRUK
##VERSION 1
##CENTRAL PEER SCRIPT
LOCATION_OF_SCRIPT=`readlink -f "$0"`

##aliases in bashrc
OPEN_CONTAINER="alias mcloud-opencontainer='$LOCATION_OF_SCRIPT openEncryptedContainer'"
CLOSE_CONTAINER="alias mcloud-closecontainer='$LOCATION_OF_SCRIPT closeEncryptedContainer'"
ADD_USER="alias mcloud-adduser='$LOCATION_OF_SCRIPT closeEncryptedContainer'"
REMOVE_USER="alias mcloud-removeuser='$LOCATION_OF_SCRIPT closeEncryptedContainer'"
MCLOUD_ITSELF="alias mcloud='$LOCATION_OF_SCRIPT'"

CONFIG_FILE_NAME="~/MCLOUD_CONFIG_SERVER"

addUser() {
	if [ ! -f $CONFIG_FILE_NAME ]; then
		    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
		    exit 1;
	fi

	eval $CONFIG_FILE_NAME

	echo "Add user to central peer using SSH-KEY PAIR"
	echo "Please make sure you changed the ssh config file to only allow ssh-key pair login"

	if [ -z "$HOME_DIRECTORY" ]; then 

		echo "Specify the location to all the home directories of the user"
		read HOME_LOCATION
	else
		HOME_LOCATION="$HOME_DIRECTORY"

	fi

	echo "Specify public key file location of user"
	read PUB_FILE
	PUB_FILE="$USERPEER_PUB_FILE"

	echo "Make sure the public key file is generated by ssh-keygen"

	CONTENTS_OF_KEY=`cat $PUB_FILE`

	echo "This will be the username to login with"
	USER_NAME=`ssh-keygen -l -f $PUB_FILE | cut -f4 -d' ' | cut -f1 -d'@'`
	echo $USER_NAME

	echo "Correct? (y/n)"
	read COR
	if [[ $COR == *"n"* ]]
	then
		echo "Specify another username: "
		read USER_NAME
	fi

	USER_HOME=$HOME_LOCATION/$USER_NAME
	echo "Home directory will be: $USER_HOME"

	echo "Adding user to central peer"

	sudo useradd -s /bin/bash -m -d $USER_HOME -c "PEER USER" -g users $USER_NAME

	sudo mkdir -p $USER_HOME/.ssh
	sudo sh -c "echo \" \" >> $USER_HOME/.ssh/authorized_keys"
	echo "Copying pub key file to location..."

	sudo sh -c "echo $CONTENTS_OF_KEY >> $USER_HOME/.ssh/authorized_keys"

	echo "Applying rights"
	sudo setfacl –m u:$USER_NAME:rwx $USER_HOME
	sudo setfacl -m other:--- $USER_HOME

	echo "Adding user to NFS share"
	sudo sh -c "echo \"  $USER_HOME  localhost(insecure,rw,sync,no_subtree_check) \" >> /etc/exports "
	echo "Exporting /etc/exports file"

	sudo /etc/init.d/nfs-kernel-server start
	sudo exportfs -a

	echo "SSH server restarting"
	/etc/init.d/ssh restart
}

removeUser() {
	echo "TODO: Removing user from central peer"
}

removeMCLOUD() {
	echo "TODO: Removing MCLOUD package"
}

#########################
# OPENING MCLOUD IMAGE  #
#########################
openEncryptedContainer() {
	echo "Opening and mounting the already created mCloud instance.."
	if [ ! -f $CONFIG_FILE_NAME ]; then
	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
	    exit 1;
	fi

	echo "Opening and mounting the already created mCloud instance.."

	eval $CONFIG_FILE_NAME
	echo "Opening the image file: $IMAGE_FILE..."
	sudo cryptsetup luksOpen $IMAGE_FILE $LOCAL_FILE_CONTAINER --key-file $KEY_FILE
	echo "Mounting encrypted container..."
	sudo mount /dev/mapper/$LOCAL_FILE_CONTAINER $LOCATION_MOUNTPOINT
	echo "Mountpoint is attached"
}


#########################
# CLOSING MCLOUD IMAGE  #
#########################
closeEncryptedContainer() {
	"Closing the already mounted mCloud image."
	if [ ! -f $CONFIG_FILE_NAME ]; then
	    echo "ERROR: MCLOUD_CONFIG_SERVER file does not exists, please run setup first."
	    exit 1;
	fi

	eval $CONFIG_FILE_NAME
	echo "Umounting mountpoint: $LOCATION_MOUNTPOINT"
	sudo umount $LOCATION_MOUNTPOINT
	echo "Closing encrypted luksvolume"
	sudo cryptsetup luksClose $LOCAL_FILE_CONTAINER 
	echo "Mountpoint is closed"
}

#########################
# INSTALL SCRIPT MCLOUD #
#########################
installMCLOUD() {
	echo "First installing packages: sudo apt-get install sshfs lvm2 cryptsetup openssh-server openssh-client nfs-kernel-server nfs-common..."
	sudo apt-get install sshfs lvm2 cryptsetup openssh-server openssh-client nfs-kernel-server nfs-common
	sudo modprobe dm-mod

	echo "Creating Mcloud config file..."
	touch $CONFIG_FILE_NAME
	sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.orig

	echo "Settings SSHD config parameters..."
	sudo sh -c "echo \"PermitRootLogin 		no\" >> /etc/ssh/sshd_config"
	sudo sh -c "echo \"PasswordAuthentication 	no\" >> /etc/ssh/sshd_config"
	sudo sh -c "echo \"UsePAM			yes\" >> /etc/ssh/sshd_config" 

	LOCAL_IP=`hostname -I | cut -f1 -d' '`
	echo "Use this shell script to setup the central peer, please look into the code before you run this"
	echo "Give full path to install location? e.g. /home/koen/MCLOUD_TEST"
	read INSTALL_LOCATION
	echo "Size of Central image? e.g. 100M"
	read IMAGE_SIZE
	echo "Central Peer image name? e.g. CENTRAL_MCLOUD"
	read CE_NAME
	echo "Would you like to set this server up as VPN server? (y/n) first_time? == y"
	read OPEN_VPN
	echo "Would you like to setup this server with the ACL permissions system? (y/n) n=assuming you already setupped the harddrive as ACL"
	read ACL_SERVER

	cd $INSTALL_LOCATION

	#create image of 100MB
	echo "Creating image..."
	dd if=/dev/zero of=$CE_NAME.img bs=1 count=0 seek=$IMAGE_SIZE


	#generate random key file
	echo "Generating random file..."
	dd if=/dev/urandom of=$CE_NAME.keyfile bs=1024 count=1


	#format encrypted
	echo "Format encrypted image..."
	sudo cryptsetup luksFormat $CE_NAME.img $CE_NAME.keyfile

	#create mkfs4 partition
	echo "Opening image..."
	sudo cryptsetup luksOpen $CE_NAME.img $CE_NAME --key-file $CE_NAME.keyfile


	echo "Creating mkfs4 partition..."
	sudo mkfs.ext4 /dev/mapper/$CE_NAME

	#mount to directory

	echo "Creating install directory..."
	mkdir $INSTALL_LOCATION/$CE_NAME

	echo "Mounting encrypted mapper..."
	sudo mount /dev/mapper/$CE_NAME $INSTALL_LOCATION/$CE_NAME
	


	if [ $OPEN_VPN == "y" ]
	then
		echo "Installing OpenVPN..."
		sudo ./central_peer_scripts/openvpn-install.sh
		echo "If you want to add clients later, run this command in this directory: sudo ./openvpn-install.sh And then select add Client."
	fi


	if [ $ACL_SERVER == "y" ]
	then
		sudo apt-get install acl
		echo "Please follow the rest of these steps online, I can't write a script that will handle all the special cases: https://help.ubuntu.com/community/FilePermissionsACLs#Enabling_ACLs_in_the_Filesystem
		"
		echo "Please run the following commands after finishing these steps: "
		echo "sudo setfacl -m g:users:rwx $INSTALL_LOCATION/$CE_NAME"
		echo "sudo setfacl -m other:--- $INSTALL_LOCATION/$CE_NAME"
		echo "sudo mkdir $INSTALL_LOCATION/$CE_NAME/home_directories"
	else
	
		echo "Appliying ACL rights."
		sudo setfacl -m g:users:rwx $INSTALL_LOCATION/$CE_NAME
		sudo setfacl -m other:--- $INSTALL_LOCATION/$CE_NAME
		sudo mkdir $INSTALL_LOCATION/$CE_NAME/home_directories
	fi

	echo "Saving MCLOUD_CONFIG_SERVER file.."

	echo "
	LOCATION_MOUNTPOINT=\"$INSTALL_LOCATION/$CE_NAME\"
	LOCAL_FILE_CONTAINER=\"$CE_NAME\"
	IMAGE_FILE=\"$INSTALL_LOCATION/$CE_NAME.img\"
	KEY_FILE=\"$INSTALL_LOCATION/$CE_NAME.keyfile\"
	HOME_DIRECTORY=\"$INSTALL_LOCATION/$CE_NAME/home_directories\"
	" > $CONFIG_FILE_NAME

	echo "Adding easy commands to BASHRC as aliases..."
	echo $OPEN_CONTAINER >> ~/.bashrc
	echo $CLOSE_CONTAINER >> ~/.bashrc
	echo $ADD_USER >> ~/.bashrc
	echo $REMOVE_USER >> ~/.bashrc
	echo $MCLOUD_ITSELF >> ~/.bashrc
	
	echo "Reloading BASHRC Contents..."
	. ~/.bashrc
	
	echo "Installation of MCLOUD is finished"
	echo "Use the following commands: mcloud-opencontainer, mcloud-closecontainer, mcloud-adduser, mcloud-removeuser, mcloud"

}

#########################
# The command line help #
#########################
display_help() {
    echo "This will run a few scripts for mCloud and this script will also ask some information before installing every component"
    echo ""
    echo "Usage: $0 [option...] { addUser | removeUser | removeMCLOUD | installMCLOUD | openEncryptedContainer | closeEncryptedContainer }" >&2
    echo ""
    echo "   -c, --configuration           Path to configuration file"
    echo "   -h, --help                    Display this help message"
    echo ""
    exit 1
}

################################
# Check if parameters options  #
# are given on the commandline #
################################
while :
do
    case "$1" in
      -c | --configuration)
 	  echo "Adding config file"
	  shift 2
          ;;
      -h | --help)
          display_help  # Call your function
          exit 0
          ;;
      --) # End of all options
          shift 2
          break
          ;;
      -*)
          echo "Error: Unknown option: $1" >&2
          ## or call function display_help
          exit 1 
          ;;
      *)  # No more options
          break
          ;;
    esac
done

###################### 
# Check if parameter #
# is set too execute #
######################
case "$1" in
  addUser)
    addUser #added
    ;;
  removeUser)
    removeUser
    ;;
  removeMCLOUD)
    removeMCLOUD	
    ;;
  installMCLOUD)
    installMCLOUD ##added
    ;;
  openEncryptedContainer)
    openEncryptedContainer ##added
    ;;
  closeEncryptedContainer)
    openEncryptedContainer  ##added
    ;;
  *)
	

     display_help
     exit 1
    ;;
esac

echo "Finishing"
