#!/bin/sh

echo "Removing old config files..."

rm /etc/mcloud-config/mcloud-client.conf
rm /etc/mcloud-config/mcloud-server.conf
rm -R /etc/mcloud-config/

echo "Removing old binaries files..."
rm /usr/bin/mcloud

echo "Purging debconf mcloud..."
echo PURGE | debconf-communicate mcloud
